GET http://localhost:3000
Accept: text/html

###
POST http://localhost:3000
Content-Type: application/json

{
    "name": "John",
    "age": 30
}

###############
## Users     ##
###############
## Get collection
GET http://localhost:3000/users

### POST collection with errors
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "John",
    "lastname": 30
}
### POST collection with success
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "Johdazefrgtn",
    "lastname": "Ddsfgoee",
    "email": "t@t.com",
    "password": "12345678"
}

### Get item
GET http://localhost:3000/users/3

### PATCH item
PATCH http://localhost:3000/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0MkB0LmNvbSIsImlhdCI6MTY4OTE3NDM5M30.-SH4mwXw8KZ8FvUFYjwRetgqhDm7OHPzvnMItC661GQ

{
    "lastname": "testFDFER"
}

### PATCH item with errors
PATCH http://localhost:3000/users/8
Content-Type: application/json

{
    "lastname": "dsqfvdfghj"
}

### Delete item
DELETE http://localhost:3000/users/1

### PUT item
PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjg5MDAyMTU0fQ.TMChGd4KMEE9Bcs2TcIU8-BeuAjtwR0MxnwgcBeLHgU

{
    "firstname": "Jane",
    "lastname": "Doe",
    "email": "t@t.com",
    "password": "12345678"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "12345678"
}