GET http://localhost:3000/

###
POST http://localhost:3000/

{
    "name": "John Doe",
    "email": "t@t.com"
}

### Users
GET http://localhost:3000/users
###
GET http://localhost:3000/users/213453456
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "t@t.com",
    "password": "123456"
}
###
GET http://localhost:3000/users/1
###
PUT http://localhost:3000/users/24
Content-Type: application/json

{
    "firstname": "John Doe",
    "email": "t2@t.com",
    "password": "123456"
}
###
PATCH http://localhost:3000/users/24
Content-Type: application/json

{
    "firstname": "Jane"
}
###
DELETE http://localhost:3000/users/1